name: Bug Report
description: File a bug report
labels: ["needs triage"]
body:
  - type: markdown
    id: importantnotice
    attributes:
      value: |
        ### Important notice
        **This repository is not a place for requesting support with a game, runner or an installer.**
        *DO NOT REPORT BUGS FOR OLD LUTRIS VERSIONS. MAKE SURE YOU UP TO DATE AND ARE USING THE LATEST VERSION AVAILABLE.
        *BUGS REPORTS SUBMITTED ON OLD VERSIONS WILL BE CLOSED WITHOUT FURTHER CONSIDERATION.
        *If you have issues installing a game or launching it*, make sure you follow our essential guides on [graphics driver installation](https://github.com/lutris/docs/blob/master/InstallingDrivers.md) and [dependencies for the wine runner](https://github.com/lutris/docs/blob/master/WineDependencies.md).
        *If you followed the guides and the issues persist*, try asking for help in our official [Lutris Discord Server](https://discord.com/invite/Pnt5CuY).
        *If you think there is a legitimate issue with our Lutris Wine builds*, open an issue in our [Lutris Wine repository](https://github.com/lutris/wine) instead.
        *If you think Lutris is missing an important feature*, try opening a *Feature Request* instead.
  - type: textarea
    id: description
    attributes:
      label: "Bug description"
      description: "A clear and detailed description of what the bug is.
      placeholder: "Tell us about your problem with Lutris in a clear and  detailed way"
    validations:
      required: true
  - type: textarea
    id: howtoreproduce
    attributes:
      label: How to Reproduce
      description: "Steps to reproduce the behavior and what should be observed in the end."
      placeholder: "Tell us step by step how we can replicate your problem and what we should see in the end"
      value: |
          Steps to reproduce the behavior:
          1. Go to '....'
          2. Click on '....'
          3. Do '....'
          4. See '....'
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected behavior"
      description: "A clear and detailed description of what you think should happen."
      placeholder: "Tell us what you expected Lutris to do"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log output
      description: "Close Lutris, launch it in the terminal using the command `lutris -d`, reproduce your issue, then paste all of the output from the terminal here. Do not shortnen/prune the output."
      placeholder: "Full output from the `lutris -d` command after reproducing the issue"
      render: shell
    validations:
      required: true
  - type: textarea
    id: sysinfo
    attributes:
      label: "System Information"
      description: "An auto-generated summary about system configuration from the Lutris settings."
      placeholder: "Paste it in this text form"
      render: shell
    validations:
      required: true
  - type: markdown
    id: systemsummarygif
    attributes:
      value: |
        ***You can obtain a quick system summary from within Lutris like this:***

        ![Peek 2021-11-12 05-09-2](https://user-images.githubusercontent.com/10602045/142093883-fb1169f2-28ab-4382-8e54-d7de9c96243e.gif)
  - type: textarea
    id: media
    attributes:
      label: Media (optional)
      description: "Screenshots or a Peek recorded GIF that showcases the problem."
      placeholder: If applicable, click on this form to activate it, then attach a GIF or a screenshot of the issue here by selecting or drag-and-dropping it
  - type: markdown
    id: peekinfo
    attributes:
      value: |
        ***Learn more about Peek and how it can record a GIF of your desktop here: https://github.com/phw/peek***
