on: [push, pull_request]

name: Testing
jobs:
  pytest:
    name: Pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print current dir
        run: pwd
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: Install Ubuntu dependencies
        run: |
          sudo apt update
          sudo apt-get install libdbus-1-dev pkg-config libgirepository1.0-dev cmake libcairo2-dev libgtk-3-dev libwebkit2gtk-4.0-dev
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          make req-python
          make dev
      - name: Run pytest
        run: |
          pytest
